<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>cronstone.ico</ApplicationIcon>
    <RootNamespace>BdoCronCalculator</RootNamespace>
    <AssemblyName>BdoCronCalculator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="cronstone.png" />
    <Resource Include="cronstone.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BdoCronCalculator.Tests\**\*" />
    <EmbeddedResource Remove="BdoCronCalculator.Tests\**\*" />
    <None Remove="BdoCronCalculator.Tests\**\*" />
    <Page Remove="BdoCronCalculator.Tests\**\*" />
    <Compile Remove="BdoCronCalculator.Mobile\**\*" />
    <EmbeddedResource Remove="BdoCronCalculator.Mobile\**\*" />
    <None Remove="BdoCronCalculator.Mobile\**\*" />
    <Page Remove="BdoCronCalculator.Mobile\**\*" />
    <Compile Remove="Publish\**\*" />
    <None Remove="Publish\**\*" />
  </ItemGroup>

</Project>
